-- v0.20.0: rozszerzona wiedza asystenta ServiceOS
INSERT INTO assistant_knowledge(slug,title,keywords,body,audience) VALUES
('service-intake-v020','Przyjęcie urządzenia',
 ARRAY['przyjęcie','przyjecie','protokół','protokol','akcesoria','stan urządzenia','stan urzadzenia','backup','blokada ekranu','hasło telefonu','haslo telefonu'],
 'Przy przyjęciu urządzenia zapisz co najmniej kontakt do klienta, markę i model, opis problemu oraz — jeśli jest dostępny — IMEI lub numer seryjny. Warto dopisać widoczny stan urządzenia i przekazane akcesoria. Nie zapisuj haseł klienta w zwykłych notatkach. Jeżeli diagnostyka wymaga kodu blokady, zastosuj procedurę punktu, która ogranicza dostęp do minimum i pozwala klientowi usunąć kod po zakończeniu. Przed operacjami mogącymi zmienić dane przypomnij o kopii zapasowej. Termin i koszt zapisuj tylko, gdy są realnie oszacowane.',
 'ALL'),
('service-flow-v020','Przepływ zlecenia',
 ARRAY['etap','status','received','diagnosis','waiting parts','in repair','repair done','ready','completed','gotowe do odbioru','zakończone'],
 'Typowy przepływ naprawy w ServiceOS prowadzi od przyjęcia przez diagnozę i naprawę do zakończenia. Status Gotowe do odbioru wymaga wcześniej etapu Naprawa zakończona oraz fizycznego powrotu urządzenia do punktu macierzystego. Podczas aktywnego transportu normalna zmiana statusu naprawy jest zablokowana. Pracownik podstawowy może przyjąć, edytować dane przyjęcia, anulować i przekazać urządzenie, ale nie zmienia zwykłych statusów naprawy.',
 'ALL'),
('transfers-v020','Przekazania i lokalizacja',
 ARRAY['przekazanie','transport','w drodze','lokalizacja','punkt macierzysty','punkt prowadzący','powrót','powrot','fizycznie'],
 'Przekazanie w ServiceOS opisuje fizyczny ruch urządzenia między punktami. Karta zlecenia rozróżnia punkt macierzysty, aktualną lokalizację i trwający transport. Podczas transportu status naprawy pozostaje zablokowany. Po naprawie wykonanej poza punktem macierzystym urządzenie musi fizycznie wrócić do domu przed oznaczeniem go jako Gotowe do odbioru.',
 'ALL'),
('customer-portal-v020','Portal klienta i kod klienta',
 ARRAY['kod klienta','identyfikator klienta','portal klienta','historia klienta','śledzenie','sledzenie','track','link klienta'],
 'Klient ma dwa różne mechanizmy: bezpieczny link śledzenia dotyczy pojedynczego zlecenia, a stały kod klienta otwiera prywatny portal całej historii serwisowej. Stałego kodu nie należy publikować na publicznym linku pojedynczego zlecenia. Kod i adres portalu są wysyłane e-mailem, a po zalogowaniu klient widzi swój kod również w portalu.',
 'ALL'),
('mail-delivery-v020','E-mail i kolejka dostawy',
 ARRAY['gmail','mail','email','kolejka','retry','ponowienie','provider id','nie wyszło','nie wyszlo','failed','sent'],
 'ServiceOS nie uznaje wiadomości za wysłaną tylko dlatego, że utworzono zlecenie. Wiadomość trafia do kolejki, a status SENT pojawia się dopiero po zaakceptowaniu jej przez Gmail i zapisaniu identyfikatora wiadomości dostawcy. Przy błędzie status jest FAILED i działa retry z narastającym odstępem. Każda próba renderuje aktualną treść, w tym kod i link portalu klienta.',
 'ALL'),
('accounts-v020','Konta, role i blokady',
 ARRAY['konto','rola','uprawnienie','blokada','zablokować','zablokowac','odblokować','odblokowac','punkt użytkownika','punkt uzytkownika','wsparcie lockon'],
 'Konto ma jedną główną rolę biznesową oraz może mieć dodatkowe uprawnienie Wsparcie LockOn. Wsparcie nie musi zastępować roli Serwisanta, Koordynatora ani Pracownika punktu. Właściciel może zmienić rolę, przypisane punkty, parametry serwisanta i dodatkowe Wsparcie LockOn. Zablokowanie konta natychmiast unieważnia jego aktywne sesje i blokuje nowe logowanie.',
 'OWNER'),
('support-handoff-v020','Bot i konsultant',
 ARRAY['konsultant','bot','wsparcie','czat','chat','dołącz','dolacz','aktywni użytkownicy','aktywni uzytkownicy'],
 'Rozmowa zaczyna się prywatnie z botem. Konsultant widzi, że użytkownik jest aktywny, ale nie widzi treści rozmowy, dopóki użytkownik nie wybierze prośby o konsultanta. Po prośbie rozmowa trafia do kolejki. Konsultant może dołączyć, odpowiadać i zamknąć rozmowę. Po dołączeniu człowieka bot przestaje automatycznie odpowiadać w tym wątku.',
 'ALL'),
('finance-v020','Rozliczenia serwisowe',
 ARRAY['rozliczenie','udział serwisanta','udzial serwisanta','procent','przychód','przychod','snapshot','firma','boss'],
 'Rozliczenia automatyczne korzystają z procentu przypisanego do konkretnego serwisanta i zapisują jego wartość w momencie tworzenia wpisu przychodowego. Dzięki temu późniejsza zmiana procentu nie zmienia historii. Widok Szefa pokazuje przychód firmy, udział serwisantów, udział firmy i rozbicie na punkty oraz zlecenia.',
 'ALL'),
('mobile-v020','Panel WWW i telefon',
 ARRAY['telefon','panel www','pwa','zaakceptować konto','zaakceptowac konto','wniosek','mobilny panel'],
 'Panel WWW/PWA korzysta z tych samych uprawnień backendowych co desktop. Właściciel może na telefonie zaakceptować oczekujący wniosek, ustawić główną rolę, punkty i dodatkowe Wsparcie LockOn, a także blokować konta. Odświeżenie PWA może wymagać przeładowania po aktualizacji service workera.',
 'ALL'),
('diagnostics-v020','Narzędzia diagnostyczne bota',
 ARRAY['test internetu','prędkość internetu','predkosc internetu','speedtest','diagnostyka','api','film','youtube','tutorial','service manual','datasheet'],
 'Bot ma narzędzia lokalne: „test internetu” lub /net mierzy łącze na urządzeniu użytkownika; „diagnostyka połączenia” lub /diag sprawdza internet i centralne API ServiceOS; „film …” lub /video otwiera wyszukiwanie instruktaży YouTube; /web i pytania o service manual, datasheet lub schemat otwierają wyszukiwanie materiałów technicznych. Dla procedur sprzętowych zawsze sprawdź dokładny model i rewizję urządzenia przed wykonaniem czynności.',
 'ALL')
ON CONFLICT (slug) DO UPDATE SET
 title=EXCLUDED.title,
 keywords=EXCLUDED.keywords,
 body=EXCLUDED.body,
 audience=EXCLUDED.audience,
 enabled=true,
 updated_at=now();

INSERT INTO schema_migrations(version,description)
VALUES ('2026-09-19-v020-assistant-knowledge','Expanded ServiceOS assistant knowledge and diagnostic tools')
ON CONFLICT (version) DO NOTHING;
