import { useEffect, useMemo, useState } from 'react';
import { Calculator, Download, FileText, PackagePlus, ReceiptText, Save, Trash2, Upload } from 'lucide-react';
import type { ServiceCosting, ServiceInvoice, ServiceOrderPart, ServiceOrderSummary } from '../types/electron';
import { useAppDialog } from './AppDialog';

interface Props { order:ServiceOrderSummary; disabled?:boolean; guided?:boolean; }
type PartDraft=Pick<ServiceOrderPart,'description'|'quantity'|'unitCostGross'|'invoiceReceived'>&{invoiceNumber?:string;supplier?:string;purchasedAt?:string};
const money=(value:number|null|undefined,currency='PLN')=>value==null?'—':new Intl.NumberFormat('pl-PL',{style:'currency',currency}).format(value);
const emptyPart=():PartDraft=>({description:'',quantity:1,unitCostGross:0,invoiceReceived:false,invoiceNumber:'',supplier:'',purchasedAt:''});

export function OrderCostingCard({order,disabled=false,guided=false}:Props){
 const {confirm}=useAppDialog(); const [data,setData]=useState<ServiceCosting|null>(null); const [parts,setParts]=useState<PartDraft[]>([]); const [labor,setLabor]=useState('0'); const [other,setOther]=useState('0'); const [invoiceMeta,setInvoiceMeta]=useState({invoiceNumber:'',supplier:'',invoiceDate:'',grossAmount:'',partDescription:''}); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 const load=async()=>{setBusy(c=>c||'load');setError('');try{const r=await window.lockOn.service.getCosting(order.id);setData(r);setLabor(String(r.laborCostGross||0));setOther(String(r.otherCostGross||0));setParts(r.parts.map(p=>({description:p.description,quantity:p.quantity,unitCostGross:p.unitCostGross,invoiceReceived:p.invoiceReceived,invoiceNumber:p.invoiceNumber||'',supplier:p.supplier||'',purchasedAt:p.purchasedAt?String(p.purchasedAt).slice(0,10):''})));}catch(e){setError(e instanceof Error?e.message:'Nie udało się pobrać rozliczenia zlecenia.');}finally{setBusy('');}};
 useEffect(()=>{void load();},[order.id]);
 const totals=useMemo(()=>{const partsCost=parts.reduce((s,p)=>s+(Number(p.quantity)||0)*(Number(p.unitCostGross)||0),0);const internal=partsCost+(Number(labor)||0)+(Number(other)||0);const customer=order.finalCost??order.estimatedCost??null;const margin=customer==null?null:Math.round((customer-internal)*100)/100;return{partsCost:Math.round(partsCost*100)/100,internal:Math.round(internal*100)/100,customer,margin};},[parts,labor,other,order.finalCost,order.estimatedCost]);
 const marginCopy=totals.customer==null?'Najpierw ustaw cenę dla klienta. Wtedy pokażemy wynik naprawy.':totals.margin==null?'':totals.margin<0?`Koszty są o ${money(Math.abs(totals.margin))} wyższe niż cena klienta. Podnieś cenę albo sprawdź wpisane koszty.`:totals.margin===0?'Cena klienta dokładnie pokrywa wpisane koszty.':`Po odjęciu wpisanych kosztów zostaje ${money(totals.margin)}.`;
 const patchPart=(i:number,p:Partial<PartDraft>)=>setParts(c=>c.map((x,n)=>n===i?{...x,...p}:x));
 const save=async()=>{if(busy||disabled)return;if(parts.some(p=>!p.description.trim())){setError('Każda część musi mieć opis.');return;}setBusy('save');setError('');setNotice('');try{const r=await window.lockOn.service.saveCosting(order.id,{laborCostGross:Number(String(labor).replace(',','.'))||0,otherCostGross:Number(String(other).replace(',','.'))||0,parts:parts.map(p=>({description:p.description.trim(),quantity:Number(p.quantity)||1,unitCostGross:Number(p.unitCostGross)||0,invoiceReceived:p.invoiceReceived,invoiceNumber:p.invoiceReceived?(p.invoiceNumber||'').trim():'',supplier:p.invoiceReceived?(p.supplier||'').trim():'',purchasedAt:p.invoiceReceived?(p.purchasedAt||''):''}))});setData(r);setNotice('Koszty części i robocizny zostały zapisane.');}catch(e){setError(e instanceof Error?e.message:'Nie udało się zapisać kosztów.');}finally{setBusy('');}};
 const uploadInvoice=async()=>{if(busy||disabled)return;setBusy('upload');setError('');setNotice('');try{const grossAmount=invoiceMeta.grossAmount===''?null:Number(String(invoiceMeta.grossAmount).replace(',','.'));const r=await window.lockOn.service.uploadInvoice(order.id,{invoiceNumber:invoiceMeta.invoiceNumber.trim(),supplier:invoiceMeta.supplier.trim(),invoiceDate:invoiceMeta.invoiceDate,grossAmount});if(r.cancelled)return;const invoice=r.invoice,desc=invoiceMeta.partDescription.trim();if(invoice&&desc&&grossAmount!=null&&Number.isFinite(grossAmount)&&grossAmount>=0){const next=[...parts,{description:desc,quantity:1,unitCostGross:grossAmount,invoiceReceived:true,invoiceNumber:invoice.invoiceNumber||invoiceMeta.invoiceNumber.trim(),supplier:invoice.supplier||invoiceMeta.supplier.trim(),purchasedAt:invoice.invoiceDate||invoiceMeta.invoiceDate}];setParts(next);setData(await window.lockOn.service.saveCosting(order.id,{laborCostGross:Number(String(labor).replace(',','.'))||0,otherCostGross:Number(String(other).replace(',','.'))||0,parts:next.map(p=>({description:p.description.trim(),quantity:Number(p.quantity)||1,unitCostGross:Number(p.unitCostGross)||0,invoiceReceived:p.invoiceReceived,invoiceNumber:(p.invoiceNumber||'').trim(),supplier:(p.supplier||'').trim(),purchasedAt:p.purchasedAt||''}))}));setNotice('Faktura dodana. Kwota została wpisana jako koszt części — cena dla klienta nie zmieniła się.');}else{setNotice('Faktura PDF została dodana do magazynu. Sama faktura nie zmienia ceny dla klienta.');await load();}setInvoiceMeta({invoiceNumber:'',supplier:'',invoiceDate:'',grossAmount:'',partDescription:''});}catch(e){setError(e instanceof Error?e.message:'Nie udało się dodać faktury PDF.');}finally{setBusy('');}};
 const downloadInvoice=async(i:ServiceInvoice)=>{if(busy)return;setBusy('download:'+i.id);try{const r=await window.lockOn.service.downloadInvoice(i.id);if(!r.cancelled)setNotice('Faktura została zapisana na komputerze.');}catch(e){setError(e instanceof Error?e.message:'Nie udało się pobrać faktury.');}finally{setBusy('');}};
 const removeInvoice=async(i:ServiceInvoice)=>{if(busy||disabled||!await confirm({title:'Usunąć fakturę z magazynu?',message:i.fileName,detail:'Dokument PDF zostanie usunięty z magazynu faktur tego zlecenia.',confirmLabel:'Usuń fakturę',tone:'danger'}))return;setBusy('delete:'+i.id);try{await window.lockOn.service.deleteInvoice(i.id);setNotice('Faktura została usunięta z magazynu.');await load();}catch(e){setError(e instanceof Error?e.message:'Nie udało się usunąć faktury.');}finally{setBusy('');}};
 return <section className="service-workspace-card service-costing-card"><div className="service-workspace-title"><Calculator size={16}/><div><strong>{guided?'Koszt naprawy i faktury':'Wycena, części i faktury'}</strong><span>Najpierw cena klienta, potem realne koszty. ServiceOS pokazuje różnicę prostym językiem.</span></div></div>
 {guided&&<div className="service-costing-guide"><strong>Jak to działa:</strong><span>1. Cena klienta to kwota uzgodniona za naprawę.</span><span>2. Faktura zakupu to Twój koszt — nie przychód.</span><span>3. Wynik pokazuje, ile zostaje po odjęciu części, robocizny i innych kosztów.</span></div>}
 {error&&<div className="service-inline-error">{error}</div>}{notice&&<div className="service-inline-success">{notice}</div>}
 <div className="service-cost-summary"><article><span>Cena dla klienta</span><strong>{money(totals.customer)}</strong></article><article><span>Koszt części</span><strong>{money(totals.partsCost)}</strong></article><article><span>Robocizna</span><strong>{money(Number(labor)||0)}</strong></article><article><span>Inne koszty</span><strong>{money(Number(other)||0)}</strong></article><article><span>Łączny koszt naprawy</span><strong>{money(totals.internal)}</strong></article><article className={(totals.margin??0)<0?'danger':''}><span>{totals.margin!=null&&totals.margin<0?'Brakuje do pokrycia kosztów':'Zostaje po kosztach'}</span><strong>{totals.margin==null?'—':money(totals.margin<0?Math.abs(totals.margin):totals.margin)}</strong></article></div>
 <div className={(totals.margin??0)<0?'service-inline-error':'service-costing-guide'}><strong>{totals.margin!=null&&totals.margin<0?'Uwaga: ta naprawa jest poniżej kosztów.':'Podsumowanie'}</strong><span>{marginCopy}</span></div>
 <div className="service-cost-inputs"><label><span>Robocizna — koszt wewnętrzny (PLN)</span><input disabled={disabled||Boolean(busy)} type="number" min="0" step="0.01" value={labor} onChange={e=>setLabor(e.target.value)}/></label><label><span>Inne koszty naprawy (PLN)</span><input disabled={disabled||Boolean(busy)} type="number" min="0" step="0.01" value={other} onChange={e=>setOther(e.target.value)}/></label></div>
 <div className="service-parts-head"><div><PackagePlus size={15}/><span>Części użyte w naprawie</span></div><button className="button small secondary" disabled={disabled||Boolean(busy)} onClick={()=>setParts(c=>[...c,emptyPart()])}><PackagePlus size={13}/> Dodaj część</button></div>
 <div className="service-parts-list">{parts.map((p,i)=><article className="service-part-row" key={i}><div className="service-part-main"><input disabled={disabled||Boolean(busy)} maxLength={240} placeholder="Np. wyświetlacz Samsung S25" value={p.description} onChange={e=>patchPart(i,{description:e.target.value})}/><div className="service-part-numbers"><label><span>Ilość</span><input disabled={disabled||Boolean(busy)} type="number" min="0.01" step="0.01" value={p.quantity} onChange={e=>patchPart(i,{quantity:Number(e.target.value)})}/></label><label><span>Cena zakupu szt. brutto</span><input disabled={disabled||Boolean(busy)} type="number" min="0" step="0.01" value={p.unitCostGross} onChange={e=>patchPart(i,{unitCostGross:Number(e.target.value)})}/></label><div><span>Koszt części</span><strong>{money((Number(p.quantity)||0)*(Number(p.unitCostGross)||0))}</strong></div></div></div><label className="service-part-invoice-check"><input disabled={disabled||Boolean(busy)} type="checkbox" checked={p.invoiceReceived} onChange={e=>patchPart(i,{invoiceReceived:e.target.checked})}/><span>Mam fakturę zakupu</span></label>{p.invoiceReceived&&<div className="service-part-invoice-meta"><input disabled={disabled||Boolean(busy)} placeholder="Numer faktury" value={p.invoiceNumber||''} onChange={e=>patchPart(i,{invoiceNumber:e.target.value})}/><input disabled={disabled||Boolean(busy)} placeholder="Dostawca" value={p.supplier||''} onChange={e=>patchPart(i,{supplier:e.target.value})}/><input disabled={disabled||Boolean(busy)} type="date" value={p.purchasedAt||''} onChange={e=>patchPart(i,{purchasedAt:e.target.value})}/></div>}<button className="service-part-remove" disabled={disabled||Boolean(busy)} title="Usuń część" onClick={()=>setParts(c=>c.filter((_,n)=>n!==i))}><Trash2 size={14}/></button></article>)}{!parts.length&&<div className="service-history-empty">Nie dodano jeszcze kosztów części.</div>}</div>
 <button className="button primary small" disabled={disabled||Boolean(busy)} onClick={()=>void save()}><Save size={13}/>{busy==='save'?'Zapisywanie…':'Zapisz koszty'}</button><div className="service-invoice-divider"/>
 <div className="service-parts-head"><div><ReceiptText size={15}/><span>Faktury zakupu PDF</span></div><small>Kwota z faktury = koszt zakupu, nie cena klienta</small></div><div className="service-invoice-upload-grid">{guided&&<input className="service-invoice-part-description" disabled={disabled||Boolean(busy)} maxLength={240} placeholder="Co kupiono? np. wyświetlacz Samsung S24" value={invoiceMeta.partDescription} onChange={e=>setInvoiceMeta({...invoiceMeta,partDescription:e.target.value})}/>}<input disabled={disabled||Boolean(busy)} placeholder="Numer faktury (opcjonalnie)" value={invoiceMeta.invoiceNumber} onChange={e=>setInvoiceMeta({...invoiceMeta,invoiceNumber:e.target.value})}/><input disabled={disabled||Boolean(busy)} placeholder="Dostawca (opcjonalnie)" value={invoiceMeta.supplier} onChange={e=>setInvoiceMeta({...invoiceMeta,supplier:e.target.value})}/><input disabled={disabled||Boolean(busy)} type="date" value={invoiceMeta.invoiceDate} onChange={e=>setInvoiceMeta({...invoiceMeta,invoiceDate:e.target.value})}/><input disabled={disabled||Boolean(busy)} type="number" min="0" step="0.01" placeholder="Kwota zakupu brutto" value={invoiceMeta.grossAmount} onChange={e=>setInvoiceMeta({...invoiceMeta,grossAmount:e.target.value})}/><button className="button secondary small" disabled={disabled||Boolean(busy)} onClick={()=>void uploadInvoice()}><Upload size={13}/>{busy==='upload'?'Wysyłanie…':guided?'Dodaj fakturę i koszt':'Dodaj FV w PDF'}</button></div>
 <div className="service-invoice-list">{(data?.invoices??[]).map(i=><article key={i.id}><FileText size={17}/><div><strong>{i.invoiceNumber||i.fileName}</strong><span>{i.supplier||'Bez dostawcy'}{i.invoiceDate?' · '+i.invoiceDate:''}{i.grossAmount!=null?' · koszt '+money(i.grossAmount):''}</span><small>{i.fileName} · {(i.sizeBytes/1024/1024).toFixed(2)} MB</small></div><button className="button small secondary" onClick={()=>void downloadInvoice(i)}><Download size={12}/> Pobierz</button><button className="button small danger-soft" disabled={disabled||Boolean(busy)} onClick={()=>void removeInvoice(i)}><Trash2 size={12}/></button></article>)}{!(data?.invoices??[]).length&&<div className="service-history-empty">Brak faktur PDF dla tego zlecenia.</div>}</div></section>;
}
