import { useEffect, useMemo, useState, type DragEvent } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, GripVertical, MailCheck, PackageCheck, RefreshCw, Smartphone, Wrench } from 'lucide-react';
import type { ServiceOrderSummary, TechnicianWorkspace } from '../types/electron';
interface Props { onOpenOrder:(order:ServiceOrderSummary)=>void; }
const pad=(v:number)=>String(v).padStart(2,'0'); const dayKey=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; const apiDate=(k:string)=>new Date(k+'T12:00:00').toISOString();
const startOfWeek=(s=new Date())=>{const d=new Date(s);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d;};
const device=(o:ServiceOrderSummary)=>[o.brand,o.model].filter(Boolean).join(' ')||'Telefon'; const statusTone=(o:ServiceOrderSummary)=>o.workflow?.flags.includes('OVERDUE')?'danger':o.workflow?.flags.includes('DUE_SOON')?'warning':o.workflow?.flags.includes('READY_FOR_PICKUP')?'ready':'default';
const easterSunday=(year:number)=>{const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(year,month-1,day);};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x;};
const holiday=(date:Date)=>{const y=date.getFullYear(),k=dayKey(date),e=easterSunday(y);const fixed:Record<string,string>={[`${y}-01-01`]:'Nowy Rok',[`${y}-01-06`]:'Trzech Króli',[`${y}-05-01`]:'Święto Pracy',[`${y}-05-03`]:'Święto Konstytucji 3 Maja',[`${y}-08-15`]:'Wniebowzięcie NMP',[`${y}-11-01`]:'Wszystkich Świętych',[`${y}-11-11`]:'Święto Niepodległości',[`${y}-12-24`]:'Wigilia',[`${y}-12-25`]:'Boże Narodzenie',[`${y}-12-26`]:'Drugi dzień Świąt'};if(fixed[k])return fixed[k];const movable=new Map([[dayKey(e),'Wielkanoc'],[dayKey(addDays(e,1)),'Poniedziałek Wielkanocny'],[dayKey(addDays(e,49)),'Zielone Świątki'],[dayKey(addDays(e,60)),'Boże Ciało']]);return movable.get(k)||null;};
const lastSunday=(year:number,month:number)=>{const d=new Date(year,month,0);d.setDate(d.getDate()-d.getDay());return dayKey(d);};
const tradingSunday=(date:Date)=>{if(date.getDay()!==0)return false;const y=date.getFullYear(),k=dayKey(date);const e=easterSunday(y),beforeEaster=dayKey(addDays(e,-7));const sundays=new Set([lastSunday(y,1),lastSunday(y,4),lastSunday(y,6),lastSunday(y,8),beforeEaster]);for(let day=1;day<=31;day++){const d=new Date(y,11,day);if(d.getMonth()===11&&d.getDay()===0&&day>=1&&day<=23&&24-day<=21)sundays.add(dayKey(d));}return sundays.has(k);};
const dayInfo=(d:Date)=>{const h=holiday(d);if(h)return{label:h,tone:'holiday'};if(d.getDay()===0)return tradingSunday(d)?{label:'Niedziela handlowa',tone:'trading'}:{label:'Niedziela · dzień wolny',tone:'off'};if(d.getDay()===6)return{label:'Sobota',tone:'weekend'};return null;};

export function TechnicianCalendar({onOpenOrder}:Props){
 const [data,setData]=useState<TechnicianWorkspace|null>(null),[weekStart,setWeekStart]=useState(()=>startOfWeek()),[selected,setSelected]=useState(()=>dayKey(new Date())); const [busy,setBusy]=useState(false),[moving,setMoving]=useState(''),[dragging,setDragging]=useState(''),[dropTarget,setDropTarget]=useState(''),[dropIndex,setDropIndex]=useState<number|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{if(busy)return;setBusy(true);setError('');try{setData(await window.lockOn.service.getTechnicianWorkspace());}catch(e){setError(e instanceof Error?e.message:'Nie udało się pobrać planu pracy.');}finally{setBusy(false);}};useEffect(()=>{void load();const t=window.setInterval(()=>{if(document.visibilityState==='visible')void load();},90000);return()=>clearInterval(t);},[]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return d;}),[weekStart]);useEffect(()=>{const ks=days.map(dayKey);if(!ks.includes(selected))setSelected(ks[0]);},[days,selected]);
 const byDay=useMemo(()=>{const r=new Map<string,ServiceOrderSummary[]>();for(const o of data?.orders??[]){if(!o.estimatedCompletionAt)continue;const d=new Date(o.estimatedCompletionAt);if(Number.isNaN(d.getTime()))continue;const k=dayKey(d),l=r.get(k)??[];l.push(o);r.set(k,l);}for(const l of r.values())l.sort((a,b)=>{const ap=Number(a.planPosition||0),bp=Number(b.planPosition||0);return ap||bp?(ap||999999)-(bp||999999):(a.workflow?.sortRank??50)-(b.workflow?.sortRank??50);});return r;},[data]);
 const selectedDate=days.find(d=>dayKey(d)===selected)??days[0],selectedOrders=byDay.get(selected)??[],backlog=(data?.orders??[]).filter(o=>!o.estimatedCompletionAt),waitingParts=(data?.orders??[]).filter(o=>o.status==='WAITING_PARTS'),ready=(data?.orders??[]).filter(o=>['REPAIR_DONE','READY'].includes(o.status)),todayKey=dayKey(new Date()),draggedOrder=dragging?(data?.orders??[]).find(o=>o.id===dragging):null;
 const canDropOn=(target:string|null,o=draggedOrder)=>{if(!o)return false;const source=o.estimatedCompletionAt?dayKey(new Date(o.estimatedCompletionAt)):null;if(source){if(!target)return false;return target>=source;}return !target||target>=todayKey;};
 const moveOrder=async(id:string,target:string|null,targetIndex=999)=>{if(moving)return;const previous=data,current=previous?.orders.find(o=>o.id===id);if(!current)return;const old=current.estimatedCompletionAt?dayKey(new Date(current.estimatedCompletionAt)):null;if(!canDropOn(target,current)){setError(old?'Terminu nie można cofnąć ani usunąć. Możesz zmienić kolejność albo przesunąć zlecenie na później.':'Nowe zlecenie możesz zaplanować na dzisiaj albo później.');return;}let idx=targetIndex;if(target&&old===target){const source=(byDay.get(target)??[]).findIndex(o=>o.id===id);if(source>=0&&source<idx)idx--;}idx=Math.max(0,idx);setMoving(id);setError('');setNotice('');try{const r=await window.lockOn.service.updatePlan(id,{estimatedCompletionAt:target?apiDate(target):null,targetIndex:idx});setData(await window.lockOn.service.getTechnicianWorkspace());if(target)setSelected(target);const label=target?new Date(target+'T12:00:00').toLocaleDateString('pl-PL',{weekday:'long',day:'2-digit',month:'long'}):'Bez terminu';setNotice(old!==target?`#${(r.order??current).orderNumber} przeniesiono: ${label}.${r.notification?.sent?' Klient dostał e-mail.':''}`:`Kolejność na ${label} została zapisana.`);}catch(e){if(previous)setData(previous);setError(e instanceof Error?e.message:'Nie udało się zmienić planu pracy.');}finally{setMoving('');setDragging('');setDropTarget('');setDropIndex(null);}};
 const dropHandlers=(target:string|null)=>({onDragOver:(e:DragEvent)=>{if(!dragging||!canDropOn(target))return;e.preventDefault();setDropTarget(target??'NO_DATE');setDropIndex(null);},onDrop:(e:DragEvent)=>{const id=e.dataTransfer.getData('text/service-order')||dragging,o=(data?.orders??[]).find(x=>x.id===id);if(!o||!canDropOn(target,o))return;e.preventDefault();void moveOrder(id,target,target?(byDay.get(target)??[]).filter(x=>x.id!==id).length:0);}});const dragProps=(o:ServiceOrderSummary)=>({draggable:!moving,onDragStart:(e:DragEvent)=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/service-order',o.id);setDragging(o.id);},onDragEnd:()=>{setDragging('');setDropTarget('');setDropIndex(null);}});
 const shiftWeek=(n:number)=>setWeekStart(c=>{const d=new Date(c);d.setDate(d.getDate()+n);return d;});const weekLabel=`${days[0].toLocaleDateString('pl-PL',{day:'2-digit',month:'short'})} – ${days[6].toLocaleDateString('pl-PL',{day:'2-digit',month:'short',year:'numeric'})}`,selectedInfo=dayInfo(selectedDate);
 return <section className="workplan-shell"><header className="workplan-head"><div><span className="eyebrow"><CalendarDays size={13}/> PLAN PRACY</span><h2>Twój tydzień — z dniami wolnymi i niedzielami handlowymi.</h2><p>Święta, dni ustawowo wolne i niedziele są oznaczone od razu. Zlecenia nadal układasz przeciąganiem.</p></div><div className="workplan-head-actions"><button className="button small secondary" onClick={()=>shiftWeek(-7)}><ChevronLeft size={15}/></button><button className="workplan-week-label" onClick={()=>{setWeekStart(startOfWeek());setSelected(todayKey);}}>{weekLabel}<small>wróć do dzisiaj</small></button><button className="button small secondary" onClick={()=>shiftWeek(7)}><ChevronRight size={15}/></button><button className="button small secondary" disabled={busy} onClick={()=>void load()}><RefreshCw size={14} className={busy?'spin':''}/></button></div></header>
 {error&&<div className="service-inline-error">{error}</div>}{notice&&<div className="service-inline-success workplan-notice"><MailCheck size={15}/>{notice}</div>}
 <div className="workplan-kpis"><div><Smartphone size={16}/><span>Aktywne</span><strong>{data?.counts.active??0}</strong></div><div><Wrench size={16}/><span>W naprawie</span><strong>{data?.counts.inRepair??0}</strong></div><div><Clock3 size={16}/><span>Czeka na części</span><strong>{data?.counts.waitingParts??0}</strong></div><div><PackageCheck size={16}/><span>Do odbioru</span><strong>{data?.counts.readyForPickup??0}</strong></div></div>
 <div className="workplan-days">{days.map(d=>{const k=dayKey(d),count=(byDay.get(k)??[]).length,info=dayInfo(d);return <button key={k} className={(k===selected?'active ':'')+(k===todayKey?'today ':'')+(info?'calendar-'+info.tone+' ':'')+(dropTarget===k?'drop-target ':'')} onClick={()=>setSelected(k)} {...dropHandlers(k)}><span>{d.toLocaleDateString('pl-PL',{weekday:'short'})}</span><strong>{d.toLocaleDateString('pl-PL',{day:'2-digit'})}</strong>{info&&<em className="workplan-day-info">{info.label}</em>}<small>{count} {count===1?'zlecenie':'zleceń'}</small></button>})}</div>
 <div className="workplan-focus"><div className="workplan-focus-head"><div><span>WYBRANY DZIEŃ{selectedInfo?' · '+selectedInfo.label.toUpperCase():''}</span><h3>{selectedDate.toLocaleDateString('pl-PL',{weekday:'long',day:'2-digit',month:'long'})}</h3></div><b>{selectedOrders.length}</b></div><div className="workplan-list" {...dropHandlers(selected)}>{selectedOrders.map((o,i)=><div key={o.id} className="workplan-drop-slot"><button className={'workplan-order '+statusTone(o)+(dragging===o.id?' dragging':'')} onClick={()=>onOpenOrder(o)} disabled={moving===o.id} {...dragProps(o)}><GripVertical size={16}/><span className="workplan-order-position">{i+1}</span><span className="workplan-order-no">#{o.orderNumber}</span><span className="workplan-order-copy"><strong>{device(o)}</strong><small>{o.customerName}</small></span><span className="workplan-order-state"><strong>{o.workflow?.attentionLabel||o.statusLabel}</strong><small>{o.workflow?.nextAction||'Otwórz szczegóły'}</small></span></button></div>)}{!selectedOrders.length&&<div className="workplan-empty"><CalendarDays size={25}/><strong>{selectedInfo?selectedInfo.label:'Ten dzień jest wolny'}</strong><span>{selectedInfo?.tone==='holiday'||selectedInfo?.tone==='off'?'To dzień wolny — zaplanuj pracę świadomie.':'Upuść tutaj zlecenie albo wybierz inny dzień.'}</span></div>}</div></div>
 <div className="workplan-queues"><section><header><span>Czeka na części</span><b>{waitingParts.length}</b></header>{waitingParts.slice(0,5).map(o=><button key={o.id} onClick={()=>onOpenOrder(o)}>#{o.orderNumber} · {device(o)}</button>)}</section><section><header><span>Do odbioru</span><b>{ready.length}</b></header>{ready.slice(0,5).map(o=><button key={o.id} onClick={()=>onOpenOrder(o)}>#{o.orderNumber} · {device(o)}</button>)}</section><section {...dropHandlers(null)}><header><span>Bez terminu</span><b>{backlog.length}</b></header>{backlog.slice(0,8).map(o=><button key={o.id} onClick={()=>onOpenOrder(o)} {...dragProps(o)}>#{o.orderNumber} · {device(o)}</button>)}</section></div></section>;
}
